namespace Models.Enums
{
    public enum ResultTypeEnum
    {
        RESULT_TYPE_OK = 0,
        RESULT_TYPE_UNKNOWN_ID = 1,
        RESULT_TYPE_INVALID_TOKEN = 2,
        RESULT_TYPE_PROTOCOL_ERROR = 3,
        RESULT_TYPE_UNKNOWN_COMMAND = 4,
        RESULT_TYPE_UNSUPPORTED_COMMAND = 5,
        RESULT_TYPE_INVALID_CONFIGURATION = 6,
        RESULT_TYPE_SSL_IS_NOT_ALLOWED = 7,
        RESULT_TYPE_INVALID_REQUEST_NUMBER = 8,
        RESULT_TYPE_INVALID_RETRY_REQUEST = 9,
        RESULT_TYPE_CANT_CANCEL_TICKET = 10,
        RESULT_TYPE_OPEN_SHIFT_TIMEOUT_EXPIRED = 11,
        RESULT_TYPE_INVALID_LOGIN_PASSWORD = 12,
        RESULT_TYPE_INCORRECT_REQUEST_DATA = 13,
        RESULT_TYPE_NOT_ENOUGH_CASH = 14,
        RESULT_TYPE_BLOCKED = 15,
        RESULT_TYPE_SERVICE_TEMPORARILY_UNAVAILABLE = 254,
        RESULT_TYPE_UNKNOWN_ERROR = 255
    }
}